### ISSUE TITLE
fix(webpack): hot reload failing after an error

### ISSUE THREAD

**Issue by davidholyko** [starter-code/binge#24]

**Comment by simonchen92** [comment]
It seems to error out in javascript and sass code changes. The error appears when we create syntactical error with the message 

Example below.
![image](https://user-images.githubusercontent.com/46136260/86056439-75be7e80-ba2b-11ea-9e25-6298da84c413.png)


For some reason...WDS stops reload on any type of errors....

**Comment by simonchen92** [comment]
Closing issue due to fix from commit #25
