### ISSUE TITLE
chore(github): add pre-commit hooks

### ISSUE THREAD

**Issue by davidholyko** [starter-code/binge#26]
reference: https://github.com/typicode/husky

pre commit should
```
eslint fix
prettier fix
```

**Comment by trybick** [comment]
Hey, would you still want this done? If so, I can pick it up

**Comment by davidholyko** [comment]
Hey Tim! that would be good. You can pick it up

**Comment by davidholyko** [comment]
This repo is not really meant to be open to the public. I'll try to find a way to make it semi private

**Comment by trybick** [comment]
Gotcha. The rules are confusing now. Don't worry about the topic then. I believe you can just add the label "hacktoberfest-accepted" to the PR (even if topic is not added)

```
PRs count if:
Submitted during the month of October AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```

https://hacktoberfest.digitalocean.com/hacktoberfest-update
